import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    wrhMainContainer: { flex: 1, backgroundColor: '#f8f9fa' },
    headerStyle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 15,
        height: 80,
    },
    wrhBodyWrapper: { paddingHorizontal: 15 },
    wrhSearchRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 15 },
    wrhInputContainer: {
        flex: 1,
        flexDirection: 'row',
        borderColor: '#D9D9D9',
        borderWidth: 1,
        borderRadius: 8,
        height: 50,
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    wrhInputField: { flex: 1, paddingHorizontal: 12, color: '#000' },
    wrhVerticalDivider: { width: 1, backgroundColor: '#D9D9D9', height: '60%' },
    wrhFilterIcon: { marginHorizontal: 10 },
    wrhSearchBtn: {
        backgroundColor: '#18b5a1',
        borderRadius: 8,
        height: 50,
        width: 50,
        marginLeft: 10,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 2,
    },
    // Card
    wrhCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 15,
        marginHorizontal: 15,
        marginBottom: 12,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
    },
    cardTitle: { fontSize: 15, fontWeight: 'bold', color: '#333' },
    cardDivider: { height: 1, backgroundColor: '#eee', marginVertical: 10 },
    cardRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    gridLabel: { fontSize: 10, color: '#999', fontWeight: 'bold' },
    gridValue: { fontSize: 14, fontWeight: 'bold', color: '#18b5a1' },
    actionRow: { flexDirection: 'row' },
    editBtn: { backgroundColor: '#18b5a1', borderRadius: 6, padding: 6, marginRight: 8 },
    deleteBtn: { backgroundColor: '#ff4444', borderRadius: 6, padding: 6 },
    // Modal
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: '85%',
        backgroundColor: '#fff',
        borderRadius: 15,
        padding: 20,
        alignItems: 'center',
    },
    modalHeading: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 15 },
    textLabel: { fontSize: 13, fontWeight: '600', color: '#666', marginBottom: 5 },
    inputContainer: {
        borderColor: '#D9D9D9',
        borderWidth: 1,
        borderRadius: 8,
        height: 48,
        backgroundColor: '#fff',
        paddingHorizontal: 10,
    },
    input: { flex: 1, color: '#000' },
    modalActionRow: { flexDirection: 'row', marginTop: 25, width: '100%', justifyContent: 'space-between' },
    modalBtn: { flex: 1, height: 45, borderRadius: 8, justifyContent: 'center', alignItems: 'center', marginHorizontal: 5 },
    btnText: { color: '#fff', fontWeight: 'bold', fontSize: 14 },
})

export default styles