import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    mainContainer: { flex: 1, backgroundColor: '#f8f9fa' },
    wrhBodyWrapper: { paddingHorizontal: 15 },
    wrhSearchRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 15 },
    wrhInputContainer: {
        flex: 1,
        flexDirection: 'row',
        borderColor: '#D9D9D9',
        borderWidth: 1,
        borderRadius: 8,
        height: 50,
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    wrhInputField: { flex: 1, paddingHorizontal: 12, color: '#000' },
    wrhVerticalDivider: { width: 1, backgroundColor: '#D9D9D9', height: '60%' },
    wrhFilterIcon: { marginHorizontal: 10 },
    wrhSearchBtn: {
        backgroundColor: '#18b5a1',
        borderRadius: 8,
        height: 50,
        width: 50,
        marginLeft: 10,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 2,
    },
    filterRow: { flexDirection: 'row', paddingHorizontal: 15, marginBottom: 10 },
    dropdownContainer: { flex: 1, marginRight: 8 },
    dropdown: {
        height: 45,
        borderColor: '#D9D9D9',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 8,
        backgroundColor: 'white',
    },
    placeholderStyle: { fontSize: 14, color: '#D9D9D9' },
    selectedTextStyle: { fontSize: 14 },
    // Card Styles
    wrhCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 15,
        marginHorizontal: 15,
        marginBottom: 12,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
    },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
    cardTitle: { fontSize: 16, fontWeight: 'bold', color: '#333' },
    cardWarehouse: { fontSize: 13, color: '#666' },
    typeBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, alignSelf: 'flex-start' },
    typeText: { fontSize: 11, fontWeight: 'bold', color: '#4f5e7b' },
    detailsGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
    gridItem: { flex: 1 },
    gridLabel: { fontSize: 10, fontWeight: 'bold', color: '#999', marginBottom: 4 },
    gridValue: { fontSize: 13, color: '#333' },
    statusRow: { flexDirection: 'row', alignItems: 'center' },
    statusText: { fontSize: 11, fontWeight: 'bold' },
    descriptionBox: { backgroundColor: '#f9f9f9', padding: 8, borderRadius: 8, marginBottom: 12 },
    descriptionText: { fontSize: 13, color: '#555' },
    cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#eee', paddingTop: 12 },
    amountText: { fontSize: 15, fontWeight: 'bold', color: '#18b5a1' },
    actionButtons: { flexDirection: 'row' },
    editBtn: { backgroundColor: '#18b5a1', borderRadius: 6, height: 32, width: 32, alignItems: 'center', justifyContent: 'center' },
    deleteBtn: { backgroundColor: '#ff0000', borderRadius: 6, height: 32, width: 32, alignItems: 'center', justifyContent: 'center', marginLeft: 8 },
})

export default styles