import { StyleSheet } from "react-native";

const rl_styles = StyleSheet.create({
    rl_container: {
        flex: 1,
        backgroundColor: '#F8F9FB',
    },
    rl_header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#FFF',
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
    },
    rl_headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2C3E50',
    },
    rl_headerButtons: {
        flexDirection: 'row',
    },
    rl_iconBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 6,
        marginLeft: 8,
    },
    rl_btnTxt: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: '600',
        marginLeft: 4,
    },
    rl_searchContainer: {
        flexDirection: 'row',
        padding: 12,
        backgroundColor: '#FFF',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#EEE',
    },
    rl_searchBox: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F2F2F2',
        borderRadius: 8,
        paddingHorizontal: 10,
        height: 40,
    },
    rl_input: {
        flex: 1,
        marginLeft: 8,
        fontSize: 14,
    },
    rl_clearBtn: {
        marginLeft: 10,
        backgroundColor: '#E74C3C',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
    },
    rl_clearTxt: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: 'bold',
    },
    rl_listContent: {
        padding: 12,
    },
    rl_card: {
        backgroundColor: '#FFF',
        borderRadius: 12,
        padding: 12,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#EDF0F2',
        elevation: 1,
        shadowColor: '#000',
        shadowOpacity: 0.02,
        shadowOffset: { width: 0, height: 1 },
    },
    rl_cardMain: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    rl_indexBadge: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#F0F3F5',
        justifyContent: 'center',
        alignItems: 'center',
    },
    rl_indexTxt: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#7F8C8D',
    },
    rl_infoCol: {
        flex: 1,
        marginLeft: 12,
    },
    rl_roleName: {
        fontSize: 15,
        fontWeight: '700',
        color: '#2C3E50',
    },
    rl_statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
        backgroundColor: '#E8F8F5',
        alignSelf: 'flex-start',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 12,
    },
    rl_dot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#1ABC9C',
        marginRight: 5,
    },
    rl_statusTxt: {
        fontSize: 11,
        color: '#1ABC9C',
        fontWeight: 'bold',
    },
    rl_actions: {
        flexDirection: 'row',
    },
    rl_actionBtn: {
        width: 32,
        height: 32,
        borderRadius: 6,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 8,
    },
    // ----------------------------------
    rl_overlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    rl_modalContainer: {
        width: '90%',
        maxWidth: 400,
    },
    rl_modalContent: {
        backgroundColor: '#FFF',
        borderRadius: 16,
        padding: 20,
        elevation: 10,
        shadowColor: '#000',
        shadowOpacity: 0.25,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 5 },
    },
    rl_modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        paddingBottom: 10,
    },
    rl_modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    rl_form: {
        marginBottom: 20,
    },
    rl_inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#555',
        marginBottom: 8,
    },
    rl_inputModal: {
        backgroundColor: '#F9FAFB',
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 8,
        padding: 12,
        fontSize: 15,
        color: '#333',
        marginBottom: 16,
    },
    rl_textArea: {
        height: 100,
        textAlignVertical: 'top',
    },
    rl_modalFooter: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
    },
    rl_btn: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
    },
    rl_cancelBtn: {
        backgroundColor: '#F3F4F6',
    },
    rl_saveBtn: {
        backgroundColor: '#1ABC9C',
    },
    rl_cancelTxt: {
        color: '#4B5563',
        fontWeight: '600',
    },
    rl_saveTxt: {
        color: '#FFF',
        fontWeight: 'bold',
        marginLeft: 6,
    },
});
export default rl_styles