import { Dimensions, StyleSheet } from "react-native";
const size = Dimensions.get('screen')

const style = StyleSheet.create({
    mainContainer: { flex: 1, backgroundColor: '#f1f5f9' },
    HeaderContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 15,
        paddingTop: 30,
        height: 80,
        elevation: 5,
    },
    headerTitle: {
        flex: 1,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
        marginLeft: 10,
    },
    rightIconsContainer: { flexDirection: 'row', alignItems: 'center' },
    iconButton: { padding: 5 },
    profileImageContainer: {
        backgroundColor: '#fff',
        width: 34,
        height: 34,
        borderRadius: 17,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 10,
    },
    filterWrapper: {
        flexDirection: 'row',
        paddingHorizontal: 10,
        paddingVertical: 15,
    },
    dropdownBox: { flex: 1, paddingHorizontal: 5 },
    dropdown: {
        height: 45,
        borderRadius: 10,
        paddingHorizontal: 12,
        backgroundColor: 'white',
        elevation: 2,
    },
    placeholderStyle: { fontSize: 14, color: '#94a3b8' },
    selectedTextStyle: { fontSize: 14, color: '#1e293b' },
    listWrapper: { paddingHorizontal: 10 },
    cardContainer: {
        backgroundColor: '#fff',
        flex: 1,
        margin: 6,
        padding: 15,
        borderRadius: 15,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    cardTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: '#64748b',
        marginBottom: 10,
    },
    cardBottomRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    cardValue: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#1e293b',
        flexShrink: 1,
    },
    cardIconContainer: {
        width: 35,
        height: 35,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
    },
});
export default style