import { StyleSheet } from "react-native";


const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f8fafc' },
    headerGradient: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 15, height: 85, paddingTop: 35 },
    headerLeft: { flexDirection: 'row', alignItems: 'center' },
    headerTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold', marginLeft: 15 },
    addIconBtn: { padding: 5 },
    searchSection: { flexDirection: 'row', padding: 15, alignItems: 'center' },
    wrhInputContainer: { flex: 1, flexDirection: 'row', backgroundColor: '#fff', borderRadius: 12, height: 50, alignItems: 'center', borderWidth: 1, borderColor: '#e2e8f0' },
    wrhInputField: { flex: 1, paddingHorizontal: 15, color: '#333' },
    wrhVerticalDivider: { width: 1, height: '50%', backgroundColor: '#e2e8f0' },
    wrhFilterIcon: { paddingHorizontal: 12 },
    searchBtn: { backgroundColor: '#18b5a1', height: 50, width: 50, borderRadius: 12, marginLeft: 10, justifyContent: 'center', alignItems: 'center' },
    filterDropdownRow: { paddingHorizontal: 15, marginBottom: 15 },
    dropdownFullWidth: { backgroundColor: '#fff', borderRadius: 10, height: 45, paddingHorizontal: 15, borderWidth: 1, borderColor: '#e2e8f0' },
    professionalCard: { backgroundColor: '#fff', borderRadius: 16, marginHorizontal: 15, marginBottom: 12, padding: 12, elevation: 2 },
    cardMainSection: { flexDirection: 'row', alignItems: 'center' },
    iconContainer: { width: 45, height: 45, borderRadius: 12, backgroundColor: '#f0fdfa', justifyContent: 'center', alignItems: 'center' },
    textContainer: { flex: 1, marginLeft: 12 },
    cityNameLabel: { fontSize: 16, fontWeight: '700', color: '#1e293b' },
    locationBadgeRow: { flexDirection: 'row', marginTop: 4 },
    subBadge: { backgroundColor: '#f1f5f9', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, marginRight: 6 },
    subBadgeText: { fontSize: 11, color: '#64748b', fontWeight: '600' },
    cardActionsColumn: { alignItems: 'center' },
    miniActionBtn: { width: 32, height: 32, borderRadius: 8, backgroundColor: '#f8fafc', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#f1f5f9' },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
    modernModalContent: { width: '90%', backgroundColor: '#fff', borderRadius: 24, paddingVertical: 20 },
    modalHandle: { width: 40, height: 4, backgroundColor: '#e2e8f0', borderRadius: 10, alignSelf: 'center', marginBottom: 15 },
    modalHeaderContainer: { paddingHorizontal: 20, marginBottom: 15 },
    modernModalTitle: { fontSize: 20, fontWeight: '800', color: '#1e293b' },
    modalBody: { paddingHorizontal: 20 },
    newInputLabel: { fontSize: 12, fontWeight: '700', color: '#475569', marginBottom: 6 },
    iconicInputContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f8fafc', borderRadius: 12, borderWidth: 1, borderColor: '#e2e8f0', marginBottom: 15, height: 50, paddingHorizontal: 12 },
    inputIcon: { marginRight: 8 },
    iconicInputField: { flex: 1, color: '#1e293b' },
    modernDropdownFull: { backgroundColor: '#f8fafc', borderRadius: 12, borderWidth: 1, borderColor: '#e2e8f0', height: 50, paddingHorizontal: 12, marginBottom: 20 },
    modalActionRow: { flexDirection: 'row', alignItems: 'center' },
    cancelBtn: { flex: 1, alignItems: 'center' },
    cancelBtnText: { color: '#94a3b8', fontWeight: '700' },
    confirmBtn: { flex: 1.5 },
    confirmGradient: { paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
    confirmText: { color: '#fff', fontWeight: '700' }
});
export default styles