import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
    mainContainer: { flex: 1, backgroundColor: '#fff' },
    body: { paddingHorizontal: 20, paddingTop: 10 },
    label: { fontSize: 14, fontWeight: '600', color: '#333', marginTop: 10 },
    inputContainer: {
        borderColor: '#E0E0E0',
        borderWidth: 1,
        borderRadius: 10,
        height: 50,
        marginTop: 8,
        paddingHorizontal: 12,
        backgroundColor: '#fdfdfd',
        justifyContent: 'center',
    },
    input: { flex: 1, color: 'black', fontSize: 15 },
    multilineInput: { height: 100, paddingVertical: 10 },
    inputFocus: { borderColor: '#18b5a1' },
    dropdown: {
        height: 50,
        borderRadius: 10,
        paddingHorizontal: 12,
        borderColor: '#E0E0E0',
        borderWidth: 1,
        marginTop: 8,
        marginBottom: 10,
    },
    placeholderStyle: { fontSize: 15, color: '#ababab' },
    selectedTextStyle: { fontSize: 15, color: '#000' },
    confirmBtn: {
        height: 55,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 30,
        elevation: 4,
    },
    btnText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
    imagePickerContainer: {
        height: 160,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: 15,
        borderStyle: 'dashed',
        marginBottom: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f9f9f9',
    },
    imagePickerText: { color: '#ababab', marginTop: 10, fontSize: 13 },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: 'white',
        width: '100%',
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        padding: 25,
        alignItems: 'center',
    },
    modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 20, color: '#333' },
    modalOption: {
        flexDirection: 'row',
        width: '100%',
        paddingVertical: 15,
        alignItems: 'center',
        gap: 15
    },
    optionText: { fontSize: 16, color: '#444' },
    divider: { height: 1, backgroundColor: '#eee', width: '100%' },
    cancelBtn: { marginTop: 15, padding: 15, width: '100%', alignItems: 'center' },
    cancelText: { color: 'red', fontWeight: 'bold', fontSize: 16 },
});
export default styles;